apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-task
spec:
  steps:
    - name: build
      image: node:14
      script: |
        #!/bin/sh
        npm install
        npm run build